# AI In Education Exploration
Since AI tools have become widely popularized in the early 2020's, one area that their usage has become popular in is education.

The original survey was as follows:

Question 1: On a scale of 1 to 10, how informed do you think you are about the concept of artificial intelligence? (1-not informed at all, 10-extremely informed)

Question 2: What sources do you use to learn about the concept of artificial intelligence?

- Internet
- Books/Scientific papers (physical/online format)
- Social media
- Discussions with family/friends
- I don't inform myself about AI

Question 3: Express your agreement or disagreement with the following statements: (Strongly Disagree, Partially Disagree, Neutral, Partially Agree, Fully Agree)

1. AI encourages dehumanization
2. Robots will replace people at work
3. AI helps to solve many problems in society (education, agriculture, medicine), managing time and dangerous situations more efficiently
4. AI will rule society

Question 4: Express your agreement or disagreement with the following statements: (Strongly Disagree, Partially Disagree, Neutral, Partially Agree, Fully Agree)

1. Machinery using AI is very expensive and resource intensive to build and maintain
2. AI will lead to a global economic crisis
3. AI will help global economic growth
4. AI leads to job losses

Question 5: When you think about AI do you feel:

- Curiosity
- Fear
- Indifference
- Trust

Question 6: In which areas do you think AI would have a big impact?

- Education
- Medicine
- Agriculture
- Constructions
- Marketing
- Public administration
- Art

Question 7: On a scale of 1 to 10, how useful do you think AI would be in the educational process? (1- not useful at all, 10-extremely useful)

Question 8: What do you think is the main advantage that AI would have in the teaching process?

- Teachers can be assisted by a virtual assistant for teaching lessons and answering students' questions immediately
- More efficient management of teachers' time
- More interactive and engaging lessons for students
- Other

Question 9: What do you think is the main advantage that AI would have in the learning process?

- Personalized lessons according to students' needs
- Universal access for all students eager to learn, including those with special needs
- More interactive and engaging lessons for students
- Other

Question 10: What do you think is the main advantage that AI would have in the evaluation process?

- Automation of exam grading
- Fewer errors in grading system
- Constant feedback from virtual assistants for each student
- Other

Question 11: What do you think is the main disadvantage that AI would have in the educational process?

- Lack of a relationship between students and teacher
- Internet addiction
- Rarer interactions between students and teachers
- Loss of information caused by possible system failure

Question 12: What is your gender?

- Female
- Male

Question 13: What is your year of study?

- Year 2
- Year 3

Question 14: What is your major?

- Economic Cybernetics
- Statistics and Economic Forecasting
- Economic Informatics

Question 15: Did you pass all your exams?

- Yes
- No

Question 16: What is your GPA for your last year of study? (Note that grades are from 1 to 10 in Romania)

- 5.0-5.4
- 5.5.-5.9
- 6.0-6.4
- 6.5-6.9
- 7.0-7.4
- 7.5-7.9
- 8.0-8.4
- 8.5-8.9
- 9.0-9.4
- 9.5-10

In [1]:
import polars as pl

df = pl.read_csv("Survey_AI.csv")

In [2]:
print("Shape:", df.shape)
print("Columns:", df.columns)

Shape: (91, 35)
Columns: ['ID', 'Q1.AI_knowledge', 'Q2.AI_sources', 'Q2#1.Internet', 'Q2#2.Books/Papers', 'Q2#3.Social_media', 'Q2#4.Discussions', 'Q2#5.NotInformed', 'Q3#1.AI_dehumanization', 'Q3#2.Job_replacement', 'Q3#3.Problem_solving', 'Q3#4.AI_rulling_society', 'Q4#1.AI_costly', 'Q4#2.Economic_crisis', 'Q4#3.Economic_growth', 'Q4#4.Job_loss', 'Q5.Feelings', 'Q6.Domains', 'Q6#1.Education', 'Q6#2.Medicine', 'Q6#3.Agriculture', 'Q6#4.Constructions', 'Q6#5.Marketing', 'Q6#6.Administration', 'Q6#7.Art', 'Q7.Utility_grade', 'Q8.Advantage_teaching', 'Q9.Advantage_learning', 'Q10.Advantage_evaluation ', 'Q11.Disadvantage_educational_process', 'Q12.Gender', 'Q13.Year_of_study', 'Q14.Major', 'Q15.Passed_exams', 'Q16.GPA']

In [3]:
df

shape: (91, 35)
┌─────┬─────────────┬─────────────┬────────────┬───┬────────────┬───────────┬────────────┬─────────┐
│ ID  ┆ Q1.AI_knowl ┆ Q2.AI_sourc ┆ Q2#1.Inter ┆ … ┆ Q13.Year_o ┆ Q14.Major ┆ Q15.Passed ┆ Q16.GPA │
│ --- ┆ edge        ┆ es          ┆ net        ┆   ┆ f_study    ┆ ---       ┆ _exams     ┆ ---     │
│ i64 ┆ ---         ┆ ---         ┆ ---        ┆   ┆ ---        ┆ i64       ┆ ---        ┆ f64     │
│     ┆ i64         ┆ str         ┆ i64        ┆   ┆ i64        ┆           ┆ i64        ┆         │
╞═════╪═════════════╪═════════════╪════════════╪═══╪════════════╪═══════════╪════════════╪═════════╡
│ 1   ┆ 8           ┆ Internet;Bo ┆ 1          ┆ … ┆ 2          ┆ 2         ┆ 1          ┆ 9.2     │
│     ┆             ┆ oks/Scienti ┆            ┆   ┆            ┆           ┆            ┆         │
│     ┆             ┆ fic pape…   ┆            ┆   ┆            ┆           ┆            ┆         │
│ 2   ┆ 7           ┆ Internet;So ┆ 1          ┆ … ┆ 2          ┆ 2         ┆ 1          ┆ 7.7     │
│     ┆             ┆ cial media  ┆            ┆   ┆            ┆           ┆            ┆         │
│ 3   ┆ 5           ┆ Internet;Bo ┆ 1          ┆ … ┆ 2          ┆ 2         ┆ 0          ┆ 7.2     │
│     ┆             ┆ oks/Scienti ┆            ┆   ┆            ┆           ┆            ┆         │
│     ┆             ┆ fic pape…   ┆            ┆   ┆            ┆           ┆            ┆         │
│ 4   ┆ 5           ┆ Internet;So ┆ 1          ┆ … ┆ 2          ┆ 2         ┆ 1          ┆ 8.2     │
│     ┆             ┆ cial media  ┆            ┆   ┆            ┆           ┆            ┆         │
│ 5   ┆ 4           ┆ Internet    ┆ 1          ┆ … ┆ 2          ┆ 2         ┆ 1          ┆ 7.7     │
│ …   ┆ …           ┆ …           ┆ …          ┆ … ┆ …          ┆ …         ┆ …          ┆ …       │
│ 87  ┆ 8           ┆ Internet    ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1          ┆ 7.2     │
│ 88  ┆ 6           ┆ Social      ┆ 0          ┆ … ┆ 1          ┆ 3         ┆ 1          ┆ 8.7     │
│     ┆             ┆ media       ┆            ┆   ┆            ┆           ┆            ┆         │
│ 89  ┆ 9           ┆ Books/Scien ┆ 0          ┆ … ┆ 1          ┆ 1         ┆ 0          ┆ 6.2     │
│     ┆             ┆ tific       ┆            ┆   ┆            ┆           ┆            ┆         │
│     ┆             ┆ papers      ┆            ┆   ┆            ┆           ┆            ┆         │
│     ┆             ┆ (physi…     ┆            ┆   ┆            ┆           ┆            ┆         │
│ 90  ┆ 2           ┆ I don't     ┆ 0          ┆ … ┆ 1          ┆ 1         ┆ 1          ┆ 8.7     │
│     ┆             ┆ inform      ┆            ┆   ┆            ┆           ┆            ┆         │
│     ┆             ┆ myself      ┆            ┆   ┆            ┆           ┆            ┆         │
│     ┆             ┆ about AI    ┆            ┆   ┆            ┆           ┆            ┆         │
│ 91  ┆ 2           ┆ Discussions ┆ 0          ┆ … ┆ 1          ┆ 3         ┆ 1          ┆ 5.2     │
│     ┆             ┆ with family ┆            ┆   ┆            ┆           ┆            ┆         │
│     ┆             ┆ /friend…    ┆            ┆   ┆            ┆           ┆            ┆         │
└─────┴─────────────┴─────────────┴────────────┴───┴────────────┴───────────┴────────────┴─────────┘

In [4]:
print("Summary:")
df.describe()

Summary:

shape: (9, 36)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic  ┆ ID       ┆ Q1.AI_kno ┆ Q2.AI_sou ┆ … ┆ Q13.Year_ ┆ Q14.Major ┆ Q15.Passe ┆ Q16.GPA  │
│ ---        ┆ ---      ┆ wledge    ┆ rces      ┆   ┆ of_study  ┆ ---       ┆ d_exams   ┆ ---      │
│ str        ┆ f64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64      │
│            ┆          ┆ f64       ┆ str       ┆   ┆ f64       ┆           ┆ f64       ┆          │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count      ┆ 91.0     ┆ 91.0      ┆ 91        ┆ … ┆ 91.0      ┆ 91.0      ┆ 91.0      ┆ 91.0     │
│ null_count ┆ 0.0      ┆ 0.0       ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ mean       ┆ 46.0     ┆ 5.912088  ┆ null      ┆ … ┆ 1.626374  ┆ 1.923077  ┆ 0.747253  ┆ 7.798901 │
│ std        ┆ 26.41338 ┆ 1.970044  ┆ null      ┆ … ┆ 0.486446  ┆ 0.763483  ┆ 0.436995  ┆ 0.975306 │
│ min        ┆ 1.0      ┆ 1.0       ┆ Books/Sci ┆ … ┆ 1.0       ┆ 1.0       ┆ 0.0       ┆ 5.2      │
│            ┆          ┆           ┆ entific   ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆           ┆ papers    ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆           ┆ (physi…   ┆   ┆           ┆           ┆           ┆          │
│ 25%        ┆ 24.0     ┆ 5.0       ┆ null      ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 7.2      │
│ 50%        ┆ 46.0     ┆ 6.0       ┆ null      ┆ … ┆ 2.0       ┆ 2.0       ┆ 1.0       ┆ 7.7      │
│ 75%        ┆ 69.0     ┆ 7.0       ┆ null      ┆ … ┆ 2.0       ┆ 3.0       ┆ 1.0       ┆ 8.7      │
│ max        ┆ 91.0     ┆ 10.0      ┆ Social    ┆ … ┆ 2.0       ┆ 3.0       ┆ 1.0       ┆ 9.7      │
│            ┆          ┆           ┆ media     ┆   ┆           ┆           ┆           ┆          │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
print("NA counts:")
df.select([pl.all().null_count()])

NA counts:

shape: (1, 35)
┌─────┬─────────────┬─────────────┬────────────┬───┬────────────┬───────────┬────────────┬─────────┐
│ ID  ┆ Q1.AI_knowl ┆ Q2.AI_sourc ┆ Q2#1.Inter ┆ … ┆ Q13.Year_o ┆ Q14.Major ┆ Q15.Passed ┆ Q16.GPA │
│ --- ┆ edge        ┆ es          ┆ net        ┆   ┆ f_study    ┆ ---       ┆ _exams     ┆ ---     │
│ u32 ┆ ---         ┆ ---         ┆ ---        ┆   ┆ ---        ┆ u32       ┆ ---        ┆ u32     │
│     ┆ u32         ┆ u32         ┆ u32        ┆   ┆ u32        ┆           ┆ u32        ┆         │
╞═════╪═════════════╪═════════════╪════════════╪═══╪════════════╪═══════════╪════════════╪═════════╡
│ 0   ┆ 0           ┆ 0           ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0          ┆ 0       │
└─────┴─────────────┴─────────────┴────────────┴───┴────────────┴───────────┴────────────┴─────────┘

## Preprocessing

In [7]:
df.columns[15:]

['Q4#4.Job_loss',
 'Q5.Feelings',
 'Q6.Domains',
 'Q6#1.Education',
 'Q6#2.Medicine',
 'Q6#3.Agriculture',
 'Q6#4.Constructions',
 'Q6#5.Marketing',
 'Q6#6.Administration',
 'Q6#7.Art',
 'Q7.Utility_grade',
 'Q8.Advantage_teaching',
 'Q9.Advantage_learning',
 'Q10.Advantage_evaluation ',
 'Q11.Disadvantage_educational_process',
 'Q12.Gender',
 'Q13.Year_of_study',
 'Q14.Major',
 'Q15.Passed_exams',
 'Q16.GPA']

In [9]:
df_new = df.rename({"Q1.AI_knowledge": "ai_knowledge_1-10", 
                "Q2.AI_sources": "ai_learning_sources", 
                "Q2#1.Internet": "learn_from_internet", 
                "Q2#2.Books/Papers": "learn_from_books_papers",
                "Q2#3.Social_media": "learn_from_social_media",
                "Q2#4.Discussions": "learn_from_discussions",
                "Q2#5.NotInformed": "not_informed_on_ai", 
                "Q3#1.AI_dehumanization": "agree_ai_dehumanization", 
                "Q3#2.Job_replacement": "agree_job_replacement",
                "Q3#3.Problem_solving": "agree_ai_problem_solving",
                "Q3#4.AI_rulling_society": "agree_ai_ruling_society",
                "Q4#1.AI_costly": "agree_ai_costly",
                "Q4#2.Economic_crisis": "agree_ai_economic_crisis",
                "Q4#3.Economic_growth": "agree_ai_economic_growth",
                "Q4#4.Job_loss": "agree_ai_job_loss",
                "Q5.Feelings": "feelings_about_ai",
                "Q6.Domains": "domains_of_ai_impact",
                "Q6#1.Education": "ai_impact_education",
                "Q6#2.Medicine": "ai_impact_medicine",
                "Q6#3.Agriculture": "ai_impact_agriculture",
                "Q6#4.Constructions": "ai_impact_construction",
                "Q6#5.Marketing": "ai_impact_marketing",
                "Q6#6.Administration": "ai_impact_administration",
                "Q6#7.Art": "ai_impact_art",
                "Q7.Utility_grade" : "grade_ai_in_education_1-10",
                "Q8.Advantage_teaching": "ai_main_advantage_teaching",
                "Q9.Advantage_learning": "ai_main_advantage_learning",
                "Q10.Advantage_evaluation ": "ai_main_advantage_evaluation",
                "Q11.Disadvantage_educational_process": "ai_main_disadvantage_educational_process",
                "Q12.Gender": "gender",
                "Q13.Year_of_study": "year_of_study",
                "Q14.Major": "major",
                "Q15.Passed_exams": "passed_exams",
                "Q16.GPA": "gpa"})

In [10]:
df_new

shape: (91, 35)
┌─────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬───────┬──────────────┬─────┐
│ ID  ┆ ai_knowledge ┆ ai_learning_ ┆ learn_from_i ┆ … ┆ year_of_stud ┆ major ┆ passed_exams ┆ gpa │
│ --- ┆ _1-10        ┆ sources      ┆ nternet      ┆   ┆ y            ┆ ---   ┆ ---          ┆ --- │
│ i64 ┆ ---          ┆ ---          ┆ ---          ┆   ┆ ---          ┆ i64   ┆ i64          ┆ f64 │
│     ┆ i64          ┆ str          ┆ i64          ┆   ┆ i64          ┆       ┆              ┆     │
╞═════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪═══════╪══════════════╪═════╡
│ 1   ┆ 8            ┆ Internet;Boo ┆ 1            ┆ … ┆ 2            ┆ 2     ┆ 1            ┆ 9.2 │
│     ┆              ┆ ks/Scientifi ┆              ┆   ┆              ┆       ┆              ┆     │
│     ┆              ┆ c pape…      ┆              ┆   ┆              ┆       ┆              ┆     │
│ 2   ┆ 7            ┆ Internet;Soc ┆ 1            ┆ … ┆ 2            ┆ 2     ┆ 1            ┆ 7.7 │
│     ┆              ┆ ial media    ┆              ┆   ┆              ┆       ┆              ┆     │
│ 3   ┆ 5            ┆ Internet;Boo ┆ 1            ┆ … ┆ 2            ┆ 2     ┆ 0            ┆ 7.2 │
│     ┆              ┆ ks/Scientifi ┆              ┆   ┆              ┆       ┆              ┆     │
│     ┆              ┆ c pape…      ┆              ┆   ┆              ┆       ┆              ┆     │
│ 4   ┆ 5            ┆ Internet;Soc ┆ 1            ┆ … ┆ 2            ┆ 2     ┆ 1            ┆ 8.2 │
│     ┆              ┆ ial media    ┆              ┆   ┆              ┆       ┆              ┆     │
│ 5   ┆ 4            ┆ Internet     ┆ 1            ┆ … ┆ 2            ┆ 2     ┆ 1            ┆ 7.7 │
│ …   ┆ …            ┆ …            ┆ …            ┆ … ┆ …            ┆ …     ┆ …            ┆ …   │
│ 87  ┆ 8            ┆ Internet     ┆ 1            ┆ … ┆ 1            ┆ 1     ┆ 1            ┆ 7.2 │
│ 88  ┆ 6            ┆ Social media ┆ 0            ┆ … ┆ 1            ┆ 3     ┆ 1            ┆ 8.7 │
│ 89  ┆ 9            ┆ Books/Scient ┆ 0            ┆ … ┆ 1            ┆ 1     ┆ 0            ┆ 6.2 │
│     ┆              ┆ ific papers  ┆              ┆   ┆              ┆       ┆              ┆     │
│     ┆              ┆ (physi…      ┆              ┆   ┆              ┆       ┆              ┆     │
│ 90  ┆ 2            ┆ I don't      ┆ 0            ┆ … ┆ 1            ┆ 1     ┆ 1            ┆ 8.7 │
│     ┆              ┆ inform       ┆              ┆   ┆              ┆       ┆              ┆     │
│     ┆              ┆ myself about ┆              ┆   ┆              ┆       ┆              ┆     │
│     ┆              ┆ AI           ┆              ┆   ┆              ┆       ┆              ┆     │
│ 91  ┆ 2            ┆ Discussions  ┆ 0            ┆ … ┆ 1            ┆ 3     ┆ 1            ┆ 5.2 │
│     ┆              ┆ with family/ ┆              ┆   ┆              ┆       ┆              ┆     │
│     ┆              ┆ friend…      ┆              ┆   ┆              ┆       ┆              ┆     │
└─────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴───────┴──────────────┴─────┘